import { Inter, Comic_Neue } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Comic_Neue({ weight:"700", subsets: ["latin"] });

export const metadata = {
  title: "SafeShare",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          {children}</body>
      </html>
    </ClerkProvider>
  );
}
